name: App test
on:
  #push:
  pull_request:
    branches:
      - main

env:
  DOT_ENV: ${{ secrets.ENV_TESTING }}
  DB_CONNECTION: mysql
  DB_DATABASE: emoji
  DB_USER: root
  DB_PASSWORD: root
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  APP_ENV: testing

permissions: read-all

jobs:
  test:
    name: Test run on ubuntu-latest php 8.2
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      # - name: Change mysql authentication method
      #   run: |
      #     mysql --host ${{ env.DB_HOST }} --port ${{ env.DB_PORT }} -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e "SHOW DATABASES"
      #     mysql --host ${{ env.DB_HOST }} --port ${{ env.DB_PORT }} -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'";

      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug
          #tools: php-cs-fixer, phpunit, pint

      - name: Copy .env
        run: cp .env.example .env

      - name: Copy .env.testing
        run: echo "${{ env.DOT_ENV }}" > .env.testing

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Generate jwt key
        run: php artisan jwt:secret

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute migrate database
        run: php artisan migrate

      - name: Execute tests coverage
        id: coverage-result
        run: php ./vendor/bin/phpunit --coverage-text
